// Code Generated by Sidekick is for learning and experimentation purposes only.
import * as React from 'react';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import MenuItem from '@mui/material/MenuItem';

const locations = [
    { value: 'HYD', label: 'Hyderabad' },
    { value: 'BENG', label: 'Bengaluru' },
    { value: 'CHE', label: 'Chennai' },
    { value: 'MUM', label: 'Mumbai' },
  ];

export default function SelectLocation() {
  return (
    <Box
      component="form"
      sx={{ '& .MuiTextField-root': { m: 1, width: '25ch' } }}
      noValidate
      autoComplete="off"
    >
      <div className='LocationDropdown'>
        <TextField
          id="outlined-select-location"
          select
          label="Select Your Location"
          defaultValue="HYD"
          sx={{
            '& .MuiInputBase-input': {
              color: 'white', // Text color
            },
            '& .MuiInputLabel-root': {
              color: 'white', // Label color
            },
            '& .MuiOutlinedInput-root': {
              '& fieldset': {
                borderColor: 'white', // Border color
              },
              '&:hover fieldset': {
                borderColor: 'white', // Border color on hover
              },
              '&.Mui-focused fieldset': {
                borderColor: 'white', // Border color when focused
              },
            },
            '& .MuiFormHelperText-root': {
              color: 'white', // Helper text color
            },
            width: '300px', // Adjust width here
            // height: '40px', // Adjust height here
          }}
        >
          {locations.map((option) => (
            <MenuItem key={option.value} value={option.value}>
              {option.label}
            </MenuItem>
          ))}
        </TextField>
      </div>
    </Box>
  );
}
